export type Account={name:string;apiToken:string;tokenFile:string;authType:"api_key"|"oauth"};
export type Config={accounts:Account[];defaultAccount:string;readOnly:boolean;allowDestructive:boolean;auditPath:string;timeoutMs:number;minIntervalMs:number;batchMinIntervalMs:number};
function integer(v:string|undefined,fallback:number,min:number,max:number){const n=v?Number(v):fallback;if(!Number.isInteger(n)||n<min||n>max)throw Error('Invalid request timeout or pacing settings.');return n;}
export function loadConfig(env:NodeJS.ProcessEnv=process.env):Config{
 let entries:Record<string,unknown>[]=[];
 if(env.FLODESK_ACCOUNTS){try{const v=JSON.parse(env.FLODESK_ACCOUNTS);if(!Array.isArray(v))throw Error();entries=v;}catch{throw Error('FLODESK_ACCOUNTS must be a private JSON array of named account profiles.');}}
 else if(env.FLODESK_API_KEY||env.FLODESK_ACCESS_TOKEN||env.FLODESK_TOKEN_FILE)entries=[{name:'default',api_key:env.FLODESK_API_KEY,access_token:env.FLODESK_ACCESS_TOKEN,token_file:env.FLODESK_TOKEN_FILE,auth_type:env.FLODESK_AUTH_TYPE}];
 const accounts=entries.map(x=>{if(!x||typeof x!=='object'||typeof x.name!=='string'||!x.name.trim())throw Error('Every Flodesk profile requires a nonempty name.');for(const k of ['api_key','access_token','token_file','auth_type'])if(x[k]!==undefined&&(typeof x[k]!=='string'||/[\r\n]/.test(x[k]as string)))throw Error('Private Flodesk profile settings must be strings without line breaks.');if(x.api_key&&x.access_token)throw Error('Private Flodesk profile must select API key or OAuth access token, never both.');const authType=x.auth_type||(x.access_token?'oauth':'api_key');if(!['api_key','oauth'].includes(authType as string)||authType==='oauth'&&x.api_key||authType==='api_key'&&x.access_token)throw Error('Private Flodesk profile auth_type must match its single credential type.');return{name:x.name.trim(),apiToken:String(x.api_key??x.access_token??''),tokenFile:String(x.token_file??''),authType:authType as 'api_key'|'oauth'};});
 if(new Set(accounts.map(a=>a.name)).size!==accounts.length)throw Error('Flodesk profile names must be unique.');
 const defaultAccount=env.FLODESK_DEFAULT_ACCOUNT??accounts[0]?.name??'';if(defaultAccount&&!accounts.some(a=>a.name===defaultAccount))throw Error('Unknown FLODESK_DEFAULT_ACCOUNT.');
 return{accounts,defaultAccount,readOnly:/^(1|true)$/i.test(env.FLODESK_READ_ONLY??''),allowDestructive:!/^(0|false)$/i.test(env.FLODESK_ALLOW_DESTRUCTIVE??''),auditPath:env.FLODESK_AUDIT_LOG??'',timeoutMs:integer(env.FLODESK_REQUEST_TIMEOUT_MS,30000,100,300000),minIntervalMs:integer(env.FLODESK_MIN_REQUEST_INTERVAL_MS,650,0,10000),batchMinIntervalMs:integer(env.FLODESK_BATCH_MIN_REQUEST_INTERVAL_MS,3100,0,60000)};
}
export function selectAccount(c:Config,hint?:string):Account{const a=c.accounts.find(a=>a.name===(hint??c.defaultAccount));if(!a)throw Error(c.accounts.length?'Unknown profile; run list_accounts and use its exact label.':'No credentials configured. Set FLODESK_API_KEY or FLODESK_TOKEN_FILE privately; run flodesk-cli login.');return a;}
