import operationsData from'./operations.json'with{type:'json'};import provenance from'./provenance.json'with{type:'json'};import{Ajv,type ValidateFunction}from'ajv';import addFormats from'ajv-formats';import{open,lstat,unlink}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';import{createHash}from'node:crypto';
import{FlodeskClient,type Json,type QueryParam}from'../api/client.js';import{FlodeskError,UsageError}from'../api/errors.js';import{selectAccount,type Config}from'../config.js';import type { Risk } from "@thenavidm/slipway";
export type Operation={name:string;operationId:string;title:string;description:string;method:string;path:string;group:string;risk:Risk;params:{name:string;key:string;in:string;required:boolean;schema:Json;style:string;explode:boolean}[];bodySchema:Json|null;bodyRequired:boolean;privateOutput:boolean};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:FlodeskClient)=>Promise<unknown>};
const operations=operationsData as unknown as Operation[];const ajv=new Ajv({allErrors:true,strict:false,formats:{int64:true}});(addFormats as unknown as(a:Ajv)=>void)(ajv);

// Each schema compiles on first use: compiling all of them at load held back the server's first answer. compileAll() runs them in tests.
const bodyValidators=new Map<string,ValidateFunction>();function bodyValidator(op:Operation):ValidateFunction{let v=bodyValidators.get(op.name);if(!v){v=ajv.compile(op.bodySchema!);bodyValidators.set(op.name,v);}return v;}

function check(v:ValidateFunction,a:unknown){if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
function fieldsFor(op:Operation){const properties:Json=Object.fromEntries(op.params.map(p=>[p.key,p.schema]));Object.assign(properties,op.bodySchema?.properties??{});properties.account={type:'string',description:'Exact configured private account profile label; not a tenant or provider account ID.'};if(op.risk!=='read')properties.confirm={type:'boolean',description:'Must be true for the requested mutation or exclusive private output file.'};if(op.bodySchema){properties.payload={...op.bodySchema,description:'Complete native JSON body; do not mix with body flags or payload_file. Arrays use repeated JSON object flags or a whole native array in a private file.'};properties.payload_file={type:'string',minLength:1,description:'Absolute regular non-symlink JSON body file, at most 1 MiB. Cannot mix with payload/body flags.'};}if(op.privateOutput)properties.output_file={type:'string',minLength:1,description:'Required absolute new private file. Exclusive 0600 creation; never overwrites or echoes PNG/embed credentials.'};return{type:'object',properties,required:[...op.params.filter(p=>p.required).map(p=>p.key),...(op.privateOutput?['output_file']:[])],additionalProperties:false};}
async function fileJSON(path:string){let f;try{if(!isAbsolute(path)||(await lstat(path)).isSymbolicLink())throw Error();f=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await f.stat();if(!stat.isFile()||stat.size>1048576)throw Error();return JSON.parse(await f.readFile('utf8'));}catch{throw new UsageError('payload_file must be an absolute regular non-symlink JSON body file, at most 1 MiB.');}finally{await f?.close();}}
function identity(body:Json){if(!(typeof body.id==='string'&&body.id.trim())&&!(typeof body.email==='string'&&body.email.trim()))throw new UsageError('Provide a nonempty subscriber id or email.');if(body.email!==undefined&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email))throw new UsageError('Invalid subscriber email.');if(body.segment_ids&&(body.segment_ids.length>50||body.segment_ids.some((x:string)=>!x.trim())))throw new UsageError('Native subscriber upsert segment_ids requires at most 50 nonempty IDs.');}
function semantics(op:Operation,args:Json,body:any){
 if(op.bodySchema&&(!body||typeof body!=='object'||!Object.keys(body).length))throw new UsageError('Provide a nonempty native request body.');
 if(op.name==='create_or_update_subscriber'||op.name==='add_subscriber_to_workflow')identity(body);
 if(op.name==='batch_create_or_update_subscribers'){if(body.subscribers.length<1||body.subscribers.length>50)throw new UsageError('Native batch requires 1–50 subscribers.');for(const s of body.subscribers)identity(s);}
 if(['add_subscriber_to_segments','remove_subscriber_from_segments'].includes(op.name)&&(!body.segment_ids.length||body.segment_ids.some((s:string)=>!s.trim())))throw new UsageError('Select at least one nonempty segment ID.');
 for(const key of ['name','label'])if(body&&body[key]!==undefined&&!body[key].trim())throw new UsageError('Provided '+key+' cannot be blank.');
 if(op.name==='create_segment'&&!body.name?.trim())throw new UsageError('Create segment requires a nonempty name.');
 if(op.name==='publish_studio_email'&&!body.html?.trim())throw new UsageError('Publishing a Studio draft requires nonempty html.');
 if(op.name==='publish_canva_email'&&!body.bundle_url)throw new UsageError('Publishing a Canva draft requires an explicit bundle_url.');
 if(body?.post_url!==undefined||body?.bundle_url!==undefined){for(const key of ['post_url','bundle_url'])if(body[key]!==undefined){let u;try{u=new URL(body[key]);}catch{throw new UsageError('Invalid '+key+' URL.');}if(u.protocol!=='https:'||u.username||u.password)throw new UsageError('Use an HTTPS '+key+' URL without credentials.');}}
 if(body?.events&&(!body.events.length||body.events.some((e:string)=>!e.trim())))throw new UsageError('Select at least one nonempty webhook event.');
}
async function prepare(op:Operation,args:Json){const flat=Object.fromEntries(Object.keys(op.bodySchema?.properties??{}).filter(k=>args[k]!==undefined).map(k=>[k,args[k]]));if((args.payload!==undefined||args.payload_file!==undefined)&&Object.keys(flat).length)throw new UsageError('Do not mix body flags with payload/payload_file.');if(args.payload!==undefined&&args.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');let body=op.bodySchema?(args.payload_file?await fileJSON(args.payload_file):args.payload??flat):undefined;if(op.bodyRequired&&args.payload===undefined&&!args.payload_file&&!Object.keys(flat).length)throw new UsageError('This operation requires a native body; inspect schema and provide body flags, payload or payload_file.');if(op.bodySchema)check(bodyValidator(op),body);semantics(op,args,body);const path=op.params.filter(p=>p.in==='path').reduce((s,p)=>s.replace('{'+p.name+'}',encodeURIComponent(String(args[p.key]))),op.path);const query:QueryParam[]=op.params.filter(p=>p.in==='query'&&args[p.key]!==undefined).map(p=>({name:p.name,value:args[p.key],explode:p.explode}));return{method:op.method,path,query,body};}
async function execute(op:Operation,args:Json,client:FlodeskClient){const call=await prepare(op,args);return client.sanitize(await client.request(call.method,call.path,call.query,call.body,args.account));}
export const ALL_TOOLS:ToolSpec[]=operations.map(op=>({...op,inputSchema:fieldsFor(op),handler:(args,client)=>execute(op,args,client)}));
const account={type:'string',description:'Exact selected private account profile; binds label, not key ownership.'};const confirm={type:'boolean',description:'Explicit approval for this exact requested ordered batch.'};
function helper(name:string,title:string,description:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL_TOOLS.push({name,title,description,group:'local_workflows',risk,inputSchema:{type:'object',properties,required,additionalProperties:false},handler});}
helper('list_accounts','List configured accounts','Local profile labels/default/auth method only. No keys, token paths, provider identity or network request.','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,auth:a.apiToken||a.tokenFile?a.authType:'not_configured',credentialSource:a.tokenFile?'token_file':a.apiToken?'private_setting':'not_configured'}))}));
helper('get_operation_schema','Inspect a current native operation','Local reviewed method/path/query/body schema and provenance for one native tool. No credentials or provider request.','read',{operation:{type:'string',enum:operations.map(o=>o.name),description:'Exact native tool name, e.g. batch_create_or_update_subscribers or publish_studio_email.'}},['operation'],async a=>({operation:operations.find(o=>o.name===a.operation),source:provenance.source,checked:provenance.checked,snapshotSha256:provenance.sanitizedSnapshotSha256}));
helper('get_oauth_userinfo','Read OAuth identity','One fixed UserInfo GET for an explicitly selected externally minted OAuth access token. API keys refuse; no refresh, OAuth login or fallback.','read',{account},[],async(a,c)=>c.sanitize(await c.request('GET','/oauth2/userinfo',[],undefined,a.account)));
const allowed=operations.filter(o=>o.risk!=='read'&&['subscribers','segments','workflows','custom_fields'].includes(o.group)).map(o=>o.name);
const tasks={type:'array',minItems:1,maxItems:20,description:'One to twenty exact ordered supported subscriber/segment/workflow/custom-field operations. Native batch upserts may affect up to50 subscribers per task; not a20-person budget.',items:{type:'object',properties:{tool:{type:'string',enum:allowed},arguments:{type:'object',description:'Actual native tool arguments without account, confirm, payload_file or output_file.'}},required:['tool','arguments'],additionalProperties:false}};
function canonical(v:any):any{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}
function hash(v:any){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
async function reviewed(args:Json,c:FlodeskClient){const selected=selectAccount(c.config,args.account);const calls=[];for(const task of args.tasks){if(!allowed.includes(task.tool))throw new UsageError('Unsupported subscriber batch tool.');if(['account','confirm','payload_file','output_file'].some(k=>task.arguments[k]!==undefined))throw new UsageError('Batch arguments cannot override account/confirmation or reference mutable payload files.');const t=ALL_TOOLS.find(t=>t.name===task.tool)!,op=operations.find(o=>o.name===task.tool)!;validateArguments(t,task.arguments);calls.push(await prepare(op,task.arguments));}return{version:1,profile:selected.name,authType:selected.authType,snapshotSha256:provenance.sanitizedSnapshotSha256,tasks:args.tasks,calls};}
helper('preview_subscriber_batch','Review exact ordered subscriber tasks','Local validation and SHA-256 of exact ordered subscriber/segment/workflow/custom-field work, selected profile label and reviewed schema. No provider reads, key load, identity check, price or rollback guarantee.','read',{tasks,account},['tasks'],async(a,c)=>{const r=await reviewed(a,c);return{...c.sanitize(r)as Json,reviewSha256:hash(r),localOnly:true,providerValidated:false,notice:'Binds profile label and exact requests/order/schema, not key ownership or changing provider state. Each native batch upsert can affect up to 50 subscribers. Preview is local input review, not a real cohort count or provider approval token.'};});
helper('submit_subscriber_batch','Execute reviewed subscriber tasks','Confirmed one-to-twenty ordered subscriber/segment/workflow/custom-field tasks. Prevalidate all and verify exact hash before first request. Stop on first failure with known results/failed index/unattempted indices; no retries, rollback or implicit continuation.','destructive',{tasks,account,confirm,review_sha256:{type:'string',pattern:'^[a-f0-9]{64}$',description:'Exact preview_subscriber_batch hash for identical requests, profile label, schema and order.'}},['tasks','review_sha256'],async(a,c)=>{const r=await reviewed(a,c);if(hash(r)!==a.review_sha256)throw new UsageError('Review hash mismatch; preview these exact tasks and selected profile again.');const knownResults:Json[]=[];for(let i=0;i<r.calls.length;i++){const call=r.calls[i]!;try{const result=c.sanitize(await c.request(call.method,call.path,call.query,call.body,r.profile));knownResults.push({index:i,tool:a.tasks[i].tool,result});if(a.tasks[i].tool==='batch_create_or_update_subscribers'){const r=result as Json;if(!Array.isArray(r.successes)||!Array.isArray(r.failures))throw new FlodeskError('Native batch receipt is incomplete; its outcome may be unknown. Inspect before repeating.');if(r.failures.length)throw new FlodeskError('Native batch returned failures inside HTTP200; successes may already have changed subscribers. Inspect every item before any repeat.');}}catch(e){const err=e as FlodeskError;throw new FlodeskError(JSON.stringify(c.sanitize({notice:'Batch stopped. Failed request may have an unknown outcome; inspect provider state before repeating. No retries or rollback.',knownResults,failedIndex:i,unattemptedIndices:r.calls.slice(i+1).map((_,j)=>i+1+j),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{requestsProcessed:true,knownResults,notice:'Native requests returned; workflow/email side effects may continue separately.'};});
const pageOp=operations.find(o=>o.name==='list_subscribers')!;
helper('save_subscriber_page','Save one private subscriber page','Confirmed one-page GET saved only to an exclusive new0600 JSON file. No CSV/cohort export, all-pages loop, overwrite, automatic upload or browser preview.','destructive',{...fieldsFor(pageOp).properties,confirm,output_file:{type:'string',minLength:1,description:'Absolute new file in an existing private directory. Restrict Windows ACLs separately.'}},['output_file'],async(a,c)=>{if(!isAbsolute(a.output_file))throw new UsageError('output_file must be absolute.');const call=await prepare(pageOp,a);let f;try{f=await open(a.output_file,'wx',0o600);}catch{throw new UsageError('Cannot exclusively create output_file.');}try{const data=c.sanitize(await c.request(call.method,call.path,call.query,call.body,a.account));const bytes=Buffer.from(JSON.stringify(data)+'\n');await f.writeFile(bytes);return{saved:true,output_file:a.output_file,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),singlePage:true};}catch(e){await f.close();f=undefined;await unlink(a.output_file).catch(()=>{});throw e;}finally{await f?.close();}});
const validators=new Map<string,ValidateFunction>();function validatorFor(tool:ToolSpec):ValidateFunction{let v=validators.get(tool.name);if(!v){v=ajv.compile(tool.inputSchema);validators.set(tool.name,v);}return v;}export function validateArguments(tool:ToolSpec,args:Json){check(validatorFor(tool),args);}
/** Compile every input and body schema, as loading once did, so a test can prove they all compile. */
export function compileAll():number{for(const t of ALL_TOOLS)validatorFor(t);for(const o of operations)if(o.bodySchema)bodyValidator(o);return validators.size+bodyValidators.size;}
export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
